/**
 * Export Engine — Generate shareable outputs from intelligence data.
 *
 * Capabilities:
 *   1. Export narrative as Markdown text
 *   2. Export decisions as structured text
 *   3. Export full executive brief (combined)
 *   4. Generate shareable link structure
 *   5. Copy to clipboard
 *
 * SaaS path: PDF generation, email delivery, S3-backed link sharing
 */

import type { ExecutiveSnapshot } from "@/lib/api/client";

// ─── Export Formats ──────────────────────────────────────────────

interface ExportResult {
  content: string;
  filename: string;
  mimeType: string;
}

// ─── Narrative Export ────────────────────────────────────────────

export function exportNarrative(snapshot: ExecutiveSnapshot): ExportResult {
  const n = snapshot.narrative;
  if (!n) {
    return { content: "No narrative available.", filename: "narrative.md", mimeType: "text/markdown" };
  }

  const lines: string[] = [
    "# Executive Intelligence Brief",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    `**Scenario:** ${snapshot.scenario_id || "—"}`,
    `**Pipeline Confidence:** ${((snapshot.scores?.confidence ?? 0) * 100).toFixed(0)}%`,
    "",
    "---",
    "",
  ];

  if (n.title?.en) {
    lines.push(`## ${n.title.en}`, "");
  }

  if (n.body?.en) {
    lines.push(n.body.en, "");
  }

  if (n.key_points && n.key_points.length > 0) {
    lines.push("## Key Findings", "");
    n.key_points.forEach((point, i) => {
      lines.push(`${i + 1}. ${point.en}`);
    });
    lines.push("");
  }

  lines.push("---", "", "*Generated by Deevo Executive Intelligence — 12-Stage Deterministic Pipeline*");

  return {
    content: lines.join("\n"),
    filename: `deevo-brief-${Date.now()}.md`,
    mimeType: "text/markdown",
  };
}

// ─── Decisions Export ────────────────────────────────────────────

export function exportDecisions(snapshot: ExecutiveSnapshot): ExportResult {
  const decisions = snapshot.decisions || [];
  if (decisions.length === 0) {
    return { content: "No decisions available.", filename: "decisions.md", mimeType: "text/markdown" };
  }

  const lines: string[] = [
    "# Decision Intelligence Report",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    `**Total Decisions:** ${decisions.length}`,
    `**Immediate:** ${decisions.filter(d => d.recommendation.priority === "immediate").length}`,
    "",
    "---",
    "",
  ];

  decisions.forEach((d, i) => {
    lines.push(
      `## ${i + 1}. ${d.recommendation.title.en}`,
      "",
      `**Priority:** ${d.recommendation.priority.replace("_", " ").toUpperCase()}`,
      `**Action:** ${d.recommendation.action.en}`,
      `**Confidence:** ${(d.recommendation.confidence * 100).toFixed(0)}%`,
      "",
    );

    if (d.explanation) {
      if (d.explanation.what_happened?.en) lines.push(`**What happened:** ${d.explanation.what_happened.en}`);
      if (d.explanation.why_it_matters?.en) lines.push(`**Why it matters:** ${d.explanation.why_it_matters.en}`);
      if (d.explanation.why_this_recommendation?.en) lines.push(`**Rationale:** ${d.explanation.why_this_recommendation.en}`);
      if (d.explanation.who_is_affected && d.explanation.who_is_affected.length > 0) {
        lines.push(`**Affected:** ${d.explanation.who_is_affected.join(", ")}`);
      }
      lines.push("");
    }

    lines.push("---", "");
  });

  lines.push("*Generated by Deevo Executive Intelligence — 12-Stage Deterministic Pipeline*");

  return {
    content: lines.join("\n"),
    filename: `deevo-decisions-${Date.now()}.md`,
    mimeType: "text/markdown",
  };
}

// ─── Full Brief Export ───────────────────────────────────────────

export function exportFullBrief(snapshot: ExecutiveSnapshot): ExportResult {
  const narrativeExport = exportNarrative(snapshot);
  const decisionsExport = exportDecisions(snapshot);

  const scores = snapshot.scores;
  const risks = snapshot.risk_register;
  const countries = snapshot.country_impacts || [];

  const header = [
    "# Deevo Executive Intelligence — Full Report",
    "",
    `**Generated:** ${new Date().toISOString()}`,
    `**Overall Score:** ${(scores?.overall_score ?? 0).toFixed(1)}`,
    `**Aggregate Risk:** ${(risks?.aggregate_risk_score ?? 0).toFixed(1)}`,
    `**Critical Risks:** ${risks?.critical_count ?? 0}`,
    `**High Risks:** ${risks?.high_count ?? 0}`,
    `**Countries Assessed:** ${countries.length}`,
    "",
    "---",
    "",
  ].join("\n");

  const countrySection = countries.length > 0
    ? [
        "## Country Impact Summary",
        "",
        "| Country | Sensitivity | Risk Level |",
        "|---------|------------|------------|",
        ...countries.map(c =>
          `| ${c.country_code} | ${c.macro_sensitivity.toFixed(0)} | ${c.risk_level} |`
        ),
        "",
        "---",
        "",
      ].join("\n")
    : "";

  return {
    content: header + countrySection + narrativeExport.content + "\n\n" + decisionsExport.content,
    filename: `deevo-full-report-${Date.now()}.md`,
    mimeType: "text/markdown",
  };
}

// ─── Clipboard Copy ──────────────────────────────────────────────

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      return true;
    } catch {
      return false;
    }
  }
}

// ─── File Download ───────────────────────────────────────────────

export function downloadFile(result: ExportResult): void {
  const blob = new Blob([result.content], { type: result.mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = result.filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Share Link (structural placeholder) ─────────────────────────

export function generateShareLink(scenarioId: string): string {
  // SaaS implementation: POST to /api/share → returns signed short URL
  const base = typeof window !== "undefined" ? window.location.origin : "https://deevo.ai";
  return `${base}/command-center?scenario=${scenarioId}`;
}
